### PR TITLE
AMDGPU agent update

### PR DESCRIPTION
**Pull request by luraess**
Target any AMDGPU

### CODE REVIEW

**Review by albert-de-montserrat — APPROVED** [review]

**Comment by albert-de-montserrat** [comment]
Great thanks a lot!

**Comment by luraess** [comment]
We need to do add the Codecov key for Buildkite to make the tests pass.

**Comment by luraess** [comment]
Need to look further into why all GPU tests are failing.

**Comment by albert-de-montserrat** [comment]
CI passed everywhere, ready to go.

**Pull request merged**
