### PR TITLE
Subgrid diffusion and minor fixes

### PR DESCRIPTION
**Pull request by albert-de-montserrat**
- Added [subgrid diffusion](https://github.com/JuliaGeodynamics/JustPIC.jl/blob/36499a636bcf2e017598a35b018247be9bd64428/src/Physics/subgrid_diffusion.jl#L17)

```julia
"""
subgrid_diffusion!(pT, T_grid, ΔT_grid, subgrid_arrays, particles::Particles, xvi,  di, dt; d = 1.0)

The `subgrid_diffusion!` function performs subgrid diffusion calculations of the temperature field at the particles `pT`.

# Arguments
- `T_grid`: Temperature at the grid vertices
- `ΔT_grid`: Temperature increment at the grid vertices
- `subgrid_arrays`: buffers needed for subgrid diffusion
- `particles::Particles`: Particles object
- `xvi`: vertex coordinates
- `di::NTuple{N,T}` : grid spacing
- `dt` : time step
"""
```

- Fixes bug where sometimes some particles close to the model domain were not getting advected. 
- When a particle is injected, it's fields are now interpolated from the neighboring particles with inverse distance interpolation

### CODE REVIEW

**Comment by albert-de-montserrat** [comment]
CC @LukasFuchs

**Comment by aelligp** [comment]
@albert-de-montserrat could the documentation from above be put into the file? Helps later with the documentation

**Comment by albert-de-montserrat** [comment]
> @albert-de-montserrat could the documentation from above be put into the file? Helps later with the documentation

yes I still need to push it

**Comment by albert-de-montserrat** [comment]
addresses #61

**Pull request merged**
