### PR TITLE
Integrators

### PR DESCRIPTION
**Pull request by albert-de-montserrat**
Introduces `AbstractAdvectionIntegrator`s so that it becomes easier to add new integration schemes if/when needed. Currently, Euler and RK2 are available

Introduces a breaking change. New syntax is:

```julia
grid_vxi =  grid_vy, grid_vy
advection!(particles, RungeKutta2(), V, grid_vxi, dt)
```

The new code dessign seems to bring  joy and hapiness to the compiler, resulting in a 25-30 % speed up

### CODE REVIEW

**Comment by boriskaus** [comment]
Does `JustPiC` currently only work with staggered grids or does it also support collocated grids?

**Comment by albert-de-montserrat** [comment]
It's specialized for staggered grids. But it would require very few modifications to make it work with collocated grids. If there's need for that I can add it soon.

**Comment by boriskaus** [comment]
`MagmaThermoKinematics` uses collocated grids, hence my question

**Comment by albert-de-montserrat** [comment]
I haven't tried whether it breaks down, but in theory if one defines the grids of `Vx`, `Vy` (and `Vz`) to be the same, it *should* work. But I will keep it in mind and add an advection method for collocated grids (during/after EGU).

**Pull request merged**
